### ISSUE TITLE
Flashing to DA14531

### ISSUE THREAD

**Issue by ChrisYeen** [SheffieldMLtracking/BLETrack#9]
How to do this?

**Comment by FloofyDwagon** [comment]
DA14531 doesn't have flash memory - have to program to OTP memory as shown here: https://lpccs-docs.renesas.com/Tutorial_SDK6/otp_prog.html

Worth noting the following:

> The ROM-based bootloader on the DA1453x does not activate the SWD ( [Serial Wire Debug Probe](https://lpccs-docs.renesas.com/Tutorial_SDK6/debug_probe.html#serial-wire-debug)) interface during the OTP-to-RAM loading process. Consequently, once you program your application into OTP on the DA14531, SWD interface access to the device is no longer possible. Additionally, it’s crucial to exercise caution when programming OTP on the DA14585/86, as incorrect programming can render the device unusable. Follow these instructions meticulously to ensure proper execution.

**Comment by ChrisYeen** [comment]
DA14531 doesn't have flash memory - have to program to OTP memory as shown here: https://lpccs-docs.renesas.com/Tutorial_SDK6/otp_prog.html

Worth noting the following:

> The ROM-based bootloader on the DA1453x does not activate the SWD ( [Serial Wire Debug Probe](https://lpccs-docs.renesas.com/Tutorial_SDK6/debug_probe.html#serial-wire-debug)) interface during the OTP-to-RAM loading process. Consequently, once you program your application into OTP on the DA14531, SWD interface access to the device is no longer possible. Additionally, it’s crucial to exercise caution when programming OTP on the DA14585/86, as incorrect programming can render the device unusable. Follow these instructions meticulously to ensure proper execution.
